### ISSUE TITLE
Zola Todo

### ISSUE THREAD

**Issue by shalzz** [shalzz/shalzz.github.io#1]
- [x] Pagination to not show drafts
- [x] rss as feed.xml
- [x] Broken footnotes  (workaround)
- [x] ToC
- [x] No current_url in 404.html
- [x] inline CSS
- [ ] ~~related posts~~
- [x] Minify HTML and CSS (implemented with cloudflare workers)
